In [1]:
96+4

100

In [2]:
9-11

-2

In [3]:
85*0.5


42.5

In [4]:
55/5

11.0

In [10]:
a=12
b=8
c=a+b

In [12]:
print (c)

20


In [2]:
print("Siri the great")

Siri the great


In [1]:
number_1=int(input("Enter the 1st number"))#to get the input
number_2=int(input("Enter the 2nd number"))#to get the input

Enter the 1st number55
Enter the 2nd number22


In [3]:
sum=number_1+number_2
print(sum)

77


In [22]:
number_3=int(input("Enter the 1st number"))
number_4=int(input("Enter the 2nd number"))

Enter the 1st number 2
Enter the 2nd number 2


In [31]:
mul=number_3*number_4
mul


4

In [32]:
div=number_3/number_4
div

1.0

In [34]:
#to change the data type 
num=5
print(float(num))

5.0


In [35]:
#to find what type int 0r float or string
type(num)

int

In [36]:
#floating point
b=2.3
print(b)
type(b)

2.3


float

In [38]:
#boolean operator
a = 7 < 3 
print(a) 
type(a)

False


bool

In [39]:
a = 7 > 3
print(a)
type(a)

True


bool

In [40]:
my_string = "Machine Learning"
print(my_string)
type(my_string)

Machine Learning


str

In [43]:
print("srinath "*5)

srinath srinath srinath srinath srinath 


In [44]:
 # values from index 1 to 5-1 will be sliced
my_string= "programming"
print(my_string[1:5])

rogr


In [45]:
# step
print(my_string[0:10:2])

pormi


In [ ]:
#to concate 2 srtings
word_1 = 'Sri '
word_2 = 'nath'

print(word_1+word_2)

# list

In [48]:
my_list=[2,5,1.8,'Python',True]
print(my_list)

[2, 5, 1.8, 'Python', True]


In [54]:
# to add elements in list
my_list.append(5)
print(my_list)

[2, 5, 1.8, 'Python', True, 5, 5, 5]


In [56]:
# print elements of a list using their index
print(my_list[0])
print(my_list[2])

2
1.8


In [57]:
# lists allow duplicate values
list_1 = [1,2,3,4,5,12,2,3]
print(list_1)

[1, 2, 3, 4, 5, 12, 2, 3]


In [58]:
print(len(list_1))

8


In [59]:
# initiating an empty list
list_2 = []
print(list_2)

[]


In [60]:
list_2.append(5)
print(list_2)

[5]


In [61]:
# delete an item in a list
list_2 = [2, 3, 1.8, 'English', True, 6]
print(list_2)

del list_2[2]
print(list_2)

[2, 3, 1.8, 'English', True, 6]
[2, 3, 'English', True, 6]


In [62]:
# join two lists
list_3 = [1,2,3,4,5]
list_4 = [6,7,8,9,10]

list_5 = list_3 + list_4
print(list_5)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# tuple

In [67]:
# tuple allows multiple data types
tuple_2 = (1,2,3.5, 'Machine Learning', False)
print(tuple_2)

(1, 2, 3.5, 'Machine Learning', False)


In tuple we cannot append the element but in list we can do #tuples are immutable

In [69]:
# converting  a list to a tuple

my_list8 = [3,4,5,6]
print(my_list8)

my_tuple = tuple(my_list8)
print(my_tuple)

[3, 4, 5, 6]
(3, 4, 5, 6)


In [70]:
print(my_tuple[0])
print(my_tuple[1])

3
4


In [71]:
print(len(my_tuple))

4


# sets

#for set we cannot call any element in set & create duplicate values

In [72]:
# set --> Curly brackets
my_set = {1,2,3,4,5}
print(my_set)
type(my_set)

{1, 2, 3, 4, 5}


set

In [73]:
print(my_set[0]) # we cannot call values in set

TypeError: 'set' object is not subscriptable

In [4]:
my_dictionary = {'name':'Siri','age':23,'country':'India'}
print(my_dictionary)
type(my_dictionary)

{'name': 'Siri', 'age': 23, 'country': 'India'}


dict

In [6]:
import numpy as np
import pandas as pd

In [8]:
6/7
round(50/10)

5

In [11]:
brac=3+9
pow(brac,4)

20736

In [33]:
x=np.log(34)
round(x,2)

3.53

In [24]:
exp=np.exp(x)
exp

34.00000000000001

In [27]:
y=pow(3,4)
y

81

In [29]:
z=np.abs(-45)
z

45

In [32]:
d=1/np.sqrt(225)
d

0.06666666666666667

In [35]:
round(d,3)

0.067

In [38]:
X1=[1,2,3,4,5,6,7,8,9]
X2=[5,6,7,8,9,10,11]
X1
X2

[5, 6, 7, 8, 9, 10, 11]

In [44]:
Y1=np.array(X1)
Y2=np.array(X2)
Y1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
Z1=Y1/2
Z1

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [48]:
X4=np.arange(0,15)
X4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
X5=np.arange(0,30,2)
X5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [53]:
X6=np.arange(1,14,2)
X6

array([ 1,  3,  5,  7,  9, 11, 13])

In [54]:
np.median(X6)

7.0

In [55]:
np.mean(X6)

7.0

In [59]:
num=np.arange(0,1001)
num

array([   0,    1,    2, ...,  998,  999, 1000])

In [60]:
np.mean(num)

500.0

In [61]:
np.median(num)

500.0

In [73]:
divby5=np.arange(0,1001,5)
divby5

array([   0,    5,   10,   15,   20,   25,   30,   35,   40,   45,   50,
         55,   60,   65,   70,   75,   80,   85,   90,   95,  100,  105,
        110,  115,  120,  125,  130,  135,  140,  145,  150,  155,  160,
        165,  170,  175,  180,  185,  190,  195,  200,  205,  210,  215,
        220,  225,  230,  235,  240,  245,  250,  255,  260,  265,  270,
        275,  280,  285,  290,  295,  300,  305,  310,  315,  320,  325,
        330,  335,  340,  345,  350,  355,  360,  365,  370,  375,  380,
        385,  390,  395,  400,  405,  410,  415,  420,  425,  430,  435,
        440,  445,  450,  455,  460,  465,  470,  475,  480,  485,  490,
        495,  500,  505,  510,  515,  520,  525,  530,  535,  540,  545,
        550,  555,  560,  565,  570,  575,  580,  585,  590,  595,  600,
        605,  610,  615,  620,  625,  630,  635,  640,  645,  650,  655,
        660,  665,  670,  675,  680,  685,  690,  695,  700,  705,  710,
        715,  720,  725,  730,  735,  740,  745,  7

In [74]:
np.mean(divby5)

500.0

In [76]:
np.median(divby5)

500.0

In [8]:
#dictionary
data={'Name': ['suba','sri','niru','rohit'],
      'age': [ '22','23','24','25'],
      'address':['trichy','madurai','chennai','goa'],
      'qualification': ['BE','MBA','Msc','Bsc']}

In [9]:
#convert the dictionary into Dataframe
df = pd.DataFrame(data)